name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ./a.out -i lenna.jpg -o lenna.yuv && cp ./a.out lenna.yuv test/ 
    - name: test and gen md5
      run: cd ./test && ./load.sh
